# Generated by Django 5.1.3 on 2024-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='destination',
            field=models.IntegerField(default=0),
        ),
    ]
