# Generated by Django 5.1.3 on 2024-12-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_feedback_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='destination',
            new_name='destinationId',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_name',
            new_name='name',
        ),
    ]
